trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'Varastokkr.IdentityAPI/**'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: "Install .NET 9 SDK"
  inputs:
    version: '9.0'

- script: dotnet build Varastokkr.IdentityAPI/Varastokkr.IdentityAPI.csproj --configuration Release
  displayName: "Build Varastokkr.IdentityAPI"

# - script: dotnet test Varastokkr.IdentityAPI.Tests/Varastokkr.IdentityAPI.Tests.csproj --configuration Release --no-build
#   displayName: "Test Varastokkr.IdentityAPI"

- script: dotnet publish Varastokkr.IdentityAPI/Varastokkr.IdentityAPI.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: "Publish Varastokkr.IdentityAPI"

- task: AzureRmWebAppDeployment@4
  displayName: "Deploy Varastokkr.IdentityAPI to Azure Web App"
  inputs:
    azureSubscription: "<Your Azure Subscription>"
    WebAppName: "<YourAzureWebAppNameForMicroservice1>"
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**'
