networks:
  my_app_network:
    driver: bridge

volumes:
  db_data:

services:
    sqlserverdb:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqlserverdb
        environment:
          SA_PASSWORD: "${SA_PASSWORD}"
          ACCEPT_EULA: "Y"
        ports:
          - "1433:1433"
        volumes:
          - db_data:/var/opt/mssql/data
        networks:
          - my_app_network
        healthcheck:
          test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P $${SA_PASSWORD} -Q 'select 1'"]
          interval: 30s
          timeout: 10s
          retries: 5
          start_period: 30s

    varastokkr.identityapi:
        image: ${DOCKER_REGISTRY-}varastokkridentityapi
        build:
          context: .
          dockerfile: Varastokkr.IdentityAPI/Dockerfile
        ports: 
          - "5000:80"
        depends_on:
          - sqlserverdb
        networks:
          - my_app_network
        environment:
          ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
          ConnectionStrings__IdentityDbConnectionString: "Server=sqlserver,1433;Database=IdentityDb;User=sa;Password=${SA_PASSWORD};Encrypt=False;"
        healthcheck:
          test: ["CMD-SHELL", "curl --fail http://localhost:80/health || exit 1"]
          interval: 30s
          timeout: 5s
          retries: 3
          start_period: 10s
        volumes:
          - ./logs:/app/logs
    

