networks:
  my_app_network:
    driver: bridge

volumes:
  db_data:

services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqlserver
        environment:
          SA_PASSWORD: "${SA_PASSWORD}"
          ACCEPT_EULA: "Y"
        ports:
          - "1433:1433"
        volumes:
          - db_data:/var/opt/mssql
        networks:
          - my_app_network

    varastokkr.identityapi:
        image: ${DOCKER_REGISTRY-}varastokkridentityapi
        build:
          context: .
          dockerfile: Varastokkr.IdentityAPI/Dockerfile
        ports: 
          - "5001:80"
        depends_on:
          - sqlserver
        networks:
          - my_app_network
        environment:
          ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
          ConnectionStrings__IdentityDbConnectionString: "Server=sqlserver,1433;Database=IdentityDb;User=sa;Password=${SA_PASSWORD};Encrypt=False;"
          ASPNETCORE_URLS: "http://+:80"
        healthcheck:
          test: ["CMD-SHELL", "curl --fail http://localhost:80/health || exit 1"]
          interval: 30s
          timeout: 5s
          retries: 3
          start_period: 10s
        volumes:
          - ./logs:/app/logs

    varastokkr.productsapi:
        image: ${DOCKER_REGISTRY-}varastokkrproductsapi
        build:
          context: .
          dockerfile: Varastokkr.ProductsAPI/Dockerfile
        ports: 
          - "5002:80"
        depends_on:
          - sqlserver
        networks:
          - my_app_network
        environment:
          ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
          ConnectionStrings__ProductDbConnectionString: "Server=sqlserver,1433;Database=ProductDb;User=sa;Password=${SA_PASSWORD};Encrypt=False;"
          ASPNETCORE_URLS: "http://+:80"
        healthcheck:
          test: ["CMD-SHELL", "curl --fail http://localhost:80/health || exit 1"]
          interval: 30s
          timeout: 5s
          retries: 3
          start_period: 10s
        volumes:
          - ./logs:/app/logs
    

