global using FluentValidation;
global using Microsoft.EntityFrameworkCore;
global using Varastokkr.ProductAPI.Dtos;
global using Varastokkr.ProductAPI.Infrastructure;
global using Varastokkr.Shared.Abstract;
global using Varastokkr.ProductAPI.Endpoints.ProductEndpoints;
global using Varastokkr.ProductAPI.Endpoints.CategoryEndpoints;
global using Varastokkr.CategorysAPI.Dtos;
global using Varastokkr.ProductAPI.Entities;