name: CI/CD Pipeline

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: varastokkr
  AZURE_CONTAINER_REGISTRY: varastokkracr
  VARASTOKKR_IDENTITYAPI_CONTAINER_APP_NAME: varastokkr-identityapi
  VARASTOKKR_IDENTITYAPI_IMAGE_NAME: varastokkr-identityapi
  ARASTOKKR_PRODUCTSAPI_CONTAINER_APP_NAME: varastokkr-productsapi
  VARASTOKKR_PRODUCTSAPI_IMAGE_NAME: varastokkr-productsapi

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Build
        run: dotnet build ./Varastokkr.IdentityAPI --configuration Release

      - name: Build
        run: dotnet build ./Varastokkr.ProductsAPI --configuration Release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push IdentityAPI to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.VARASTOKKR_IDENTITYAPI_IMAGE_NAME }}:${{ github.sha }}
          file: ./Varastokkr.IdentityAPI/Dockerfile

      - name: Build and push ProductsAPI to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.VARASTOKKR_PRODUCTSAPI_IMAGE_NAME }}:${{ github.sha }}
          file: ./Varastokkr.ProductsAPI/Dockerfile

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install/Update Container Apps Extension
        run: az extension add --name containerapp --upgrade

      - name: Register Microsoft.App
        run: az provider register --namespace Microsoft.App --wait

      - name: Deploy IdentityAPI to Azure Web Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.VARASTOKKR_IDENTITYAPI_CONTAINER_APP_NAME }}
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.VARASTOKKR_IDENTITYAPI_IMAGE_NAME }}:${{ github.sha }}
          registryCredentials:
            server=${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
            username=${{ secrets.AZURE_REGISTRY_USERNAME }}
            password=${{ secrets.AZURE_REGISTRY_PASSWORD }}
          environmentVariables:
            ASPNETCORE_ENVIRONMENT=Development

      - name: Deploy ProductsAPI to Azure Web Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.VARASTOKKR_PRODUCTSAPI_CONTAINER_APP_NAME }}
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.VARASTOKKR_PRODUCTSAPI_IMAGE_NAME }}:${{ github.sha }}
          registryCredentials:
            server=${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
            username=${{ secrets.AZURE_REGISTRY_USERNAME }}
            password=${{ secrets.AZURE_REGISTRY_PASSWORD }}
          environmentVariables:
            ASPNETCORE_ENVIRONMENT=Development
